# Generated by Django 4.1.7 on 2023-02-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_group_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа'),
        ),
    ]
