# Generated by Django 4.1.7 on 2023-02-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_id',
        ),
    ]
