# Generated by Django 4.1.7 on 2023-02-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
