# Generated by Django 4.1.7 on 2023-02-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.group', verbose_name='Группа'),
        ),
    ]
