# Generated by Django 4.1.7 on 2023-02-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
    ]
